services:
  db:
    image: postgres:15-alpine
    container_name: event_db
    restart: unless-stopped
    env_file:
      - ./server/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./server
    container_name: event_backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./server:/app
      - /app/node_modules

  frontend:
    build:
      context: ./client
    env_file:
      - ./client/.env
    container_name: event_frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./client:/app
      - /app/node_modules

volumes:
  postgres_data:
